// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"NoticeServices/app/model/internal"
)

// App is the golang structure for table app.
type App internal.App

// Fill with you ideas below.

type AppData struct {
	Name    string `orm:"name"         json:"name"`    //
	Explain string `orm:"explain"      json:"explain"` //
}
