// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"NoticeServices/app/model/internal"
)

// Config is the golang structure for table config.
type Config internal.Config

// Fill with you ideas below.
