// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"NoticeServices/app/model/internal"
)

// Info is the golang structure for table info.
type Info internal.Info

// Fill with you ideas below.

type InfoData struct {
	AppId      string `orm:"app_id"      json:"app_id"`      //
	ConfigId   string `orm:"config_id"   json:"config_id"`   //
	ComeFrom   string `orm:"come_from"   json:"come_from"`   //
	Method     string `orm:"method"      json:"method"`      //
	MethodTask string `orm:"method_task" json:"method_task"` //
	MethodNum  int    `orm:"method_num"  json:"method_num"`  //
	MsgTitle   string `orm:"msg_title"   json:"msg_title"`   //
	MsgBody    string `orm:"msg_body"    json:"msg_body"`    //
	MsgUrl     string `orm:"msg_url"     json:"msg_url"`     //
	UserIds    string `orm:"user_ids"    json:"user_ids"`    //
	PartyIds   string `orm:"party_ids"   json:"party_ids"`   //
	Totag      string `orm:"totag"       json:"totag"`       //
}
