// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"NoticeServices/app/model/internal"
)

// Job is the golang structure for table job.
type Job internal.Job

// Fill with you ideas below.
