// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"NoticeServices/app/model/internal"
)

// SqliteSequence is the golang structure for table sqlite_sequence.
type SqliteSequence internal.SqliteSequence

// Fill with you ideas below.
