// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"NoticeServices/app/model/internal"
)

// Template is the golang structure for table template.
type Template internal.Template

// Fill with you ideas below.
