// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"NoticeServices/app/model/internal"
)

// Template is the golang structure for table template.
type Template internal.Template

// Fill with you ideas below.
type TemplateData struct {
	ConfigId    string `orm:"config_id"    json:"config_id"`    //
	SendGateway string `orm:"send_gateway" json:"send_gateway"` //
	Title       string `orm:"title"        json:"title"`        //
	Content     string `orm:"content"      json:"content"`      //
}
type TemplateUpData struct {
	TemplateData
	Id string
}
