// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"NoticeServices/app/model/internal"
)

// UserInfo is the golang structure for table userInfo.
type UserInfo internal.UserInfo

// Fill with you ideas below.
