// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// App is the golang structure for table app.
type App struct {
	Id          string `orm:"id"           json:"id"`           //
	Name        string `orm:"name"         json:"name"`         //
	Explain     string `orm:"explain"      json:"explain"`      //
	AccessToken string `orm:"access_token" json:"access_token"` //
	CreateTime  int    `orm:"create_time"  json:"create_time"`  //
}
