// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Config is the golang structure for table config.
type Config struct {
	Id          string `orm:"id"           json:"id"`           //
	AppId       string `orm:"app_id"       json:"app_id"`       //
	Name        string `orm:"name"         json:"name"`         //
	SendGateway string `orm:"send_gateway" json:"send_gateway"` //
	CreateTime  int    `orm:"create_time"  json:"create_time"`  //
	Type        string `orm:"type"         json:"type"`         //
}
