// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Info is the golang structure for table info.
type Info struct {
	Id         int    `orm:"id"          json:"id"`          //
	AppId      string `orm:"app_id"      json:"app_id"`      //
	ConfigId   string `orm:"config_id"   json:"config_id"`   //
	ComeFrom   string `orm:"come_from"   json:"come_from"`   //
	Method     string `orm:"method"      json:"method"`      //
	MsgTitle   string `orm:"msg_title"   json:"msg_title"`   //
	MsgBody    string `orm:"msg_body"    json:"msg_body"`    //
	MsgUrl     string `orm:"msg_url"     json:"msg_url"`     //
	UserIds    string `orm:"user_ids"    json:"user_ids"`    //
	PartyIds   string `orm:"party_ids"   json:"party_ids"`   //
	Totag      string `orm:"totag"       json:"totag"`       //
	State      string `orm:"state"       json:"state"`       //
	CreateTime int    `orm:"create_time" json:"create_time"` //
	MethodCron string `orm:"method_cron" json:"method_cron"` //
	MethodNum  int    `orm:"method_num"  json:"method_num"`  //
}
