// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Job is the golang structure for table job.
type Job struct {
	Id             int    `orm:"id"              json:"id"`              //
	Name           string `orm:"name"            json:"name"`            //
	Params         string `orm:"params"          json:"params"`          //
	Group          string `orm:"group"           json:"group"`           //
	InvokeTarget   string `orm:"invoke_target"   json:"invoke_target"`   //
	CronExpression string `orm:"cron_expression" json:"cron_expression"` //
	MisfirePolicy  int    `orm:"misfire_policy"  json:"misfire_policy"`  //
	Concurrent     int    `orm:"concurrent"      json:"concurrent"`      //
	Status         int    `orm:"status"          json:"status"`          //
	CreateTime     int    `orm:"create_time"     json:"create_time"`     //
	Remark         string `orm:"remark"          json:"remark"`          //
}
