// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// SqliteSequence is the golang structure for table sqlite_sequence.
type SqliteSequence struct {
	Name string `orm:"name" json:"name"` //
	Seq  string `orm:"seq"  json:"seq"`  //
}
