// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// UserInfo is the golang structure for table userInfo.
type UserInfo struct {
	Id         int    `orm:"id"          json:"id"`          //
	AppId      string `orm:"app_id"      json:"app_id"`      //
	InfoId     int    `orm:"info_id"     json:"info_id"`     //
	Status     string `orm:"status"      json:"status"`      //
	CreateTime int    `orm:"create_time" json:"create_time"` //
	UserId     string `orm:"user_id"     json:"user_id"`     //
}
