// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package define

type AppData struct {
	Name    string `orm:"name"         json:"name"`    //
	Explain string `orm:"explain"      json:"explain"` //
}
