// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"NoticeServices/app/dao/internal"
)

// appDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type appDao struct {
	*internal.AppDao
}

var (
	// App is globally public accessible object for table app operations.
	App = appDao{
		internal.NewAppDao(),
	}
)

// Fill with you ideas below.
