// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"NoticeServices/app/dao/internal"
)

// infoDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type infoDao struct {
	*internal.InfoDao
}

var (
	// Info is globally public accessible object for table info operations.
	Info = infoDao{
		internal.NewInfoDao(),
	}
)

// Fill with you ideas below.
