// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"NoticeServices/app/dao/internal"
)

// sqliteSequenceDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sqliteSequenceDao struct {
	*internal.SqliteSequenceDao
}

var (
	// SqliteSequence is globally public accessible object for table sqlite_sequence operations.
	SqliteSequence = &sqliteSequenceDao{
		internal.SqliteSequence,
	}
)

// Fill with you ideas below.
