// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"NoticeServices/app/dao/internal"
)

// templateDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type templateDao struct {
	*internal.TemplateDao
}

var (
	// Template is globally public accessible object for table template operations.
	Template = templateDao{
		internal.NewTemplateDao(),
	}
)

// Fill with you ideas below.
