// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"NoticeServices/app/dao/internal"
)

// userInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type userInfoDao struct {
	*internal.UserInfoDao
}

var (
	// UserInfo is globally public accessible object for table userInfo operations.
	UserInfo = &userInfoDao{
		internal.UserInfo,
	}
)

// Fill with you ideas below.
