// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// TemplateDao is the manager for logic model data accessing and custom defined data operations functions management.
type TemplateDao struct {
	Table   string          // Table is the underlying table name of the DAO.
	Group   string          // Group is the database configuration group name of current DAO.
	Columns TemplateColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// TemplateColumns defines and stores column names for table template.
type TemplateColumns struct {
	Id          string //
	ConfigId    string //
	SendGateway string //
	Code        string //
	Title       string //
	Content     string //
	CreateTime  string //
}

//  templateColumns holds the columns for table template.
var templateColumns = TemplateColumns{
	Id:          "id",
	ConfigId:    "config_id",
	SendGateway: "send_gateway",
	Code:        "code",
	Title:       "title",
	Content:     "content",
	CreateTime:  "create_time",
}

// NewTemplateDao creates and returns a new DAO object for table data access.
func NewTemplateDao() *TemplateDao {
	return &TemplateDao{
		Group:   "default",
		Table:   "template",
		Columns: templateColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TemplateDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TemplateDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TemplateDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
